version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    volumes:
      - kafka_data:/var/lib/kafka/data
    restart: unless-stopped

  redis:
    image: redis:7.4.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  authservice:
    image: huutri0412/authservice:latest
    container_name: authservice
    ports:
      - "8081:8081"
    depends_on:
      - redis
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    restart: unless-stopped

  checkinservice:
    image: huutri0412/checkinservice:latest
    container_name: checkinservice
    ports:
      - "8082:8082"
    depends_on:
      - kafka
      - redis
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    restart: unless-stopped

  ticketmanagementservice:
    image: huutri0412/ticketmanagementservice:latest
    container_name: ticketmanagementservice
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - redis
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    restart: unless-stopped

  apigateway:
    image: huutri0412/apigateway:latest
    container_name: apigateway
    ports:
      - "8080:8080"
    depends_on:
      - authservice
      - checkinservice
      - ticketmanagementservice
    environment:
      - AUTH_SERVICE_URL=http://authservice:8081
      - CHECKIN_SERVICE_URL=http://checkinservice:8082
      - TICKET_MANAGEMENT_SERVICE_URL=http://ticketmanagementservice:8083
    restart: unless-stopped

volumes:
  redis_data:
  kafka_data:
  zookeeper_data:
